#!/sbin/sh
#
# /system/addon.d/99-spirit2.sh (root:root 755)
# During an upgrade, this script backs up Spirit2-related files,
# /system is formatted and reinstalled, then the files are restored.
#

. /tmp/backuptool.functions

FILE=lib/hw/audio.primary.smdk4x12.so
#S1_SO_HCI=/data/data/com.mikersmicros.fm_unlock/lib/libbt-hci.so
#S2_SO_HCI=/data/data/fm.a2d.sX/lib/libbt-hci.so

NORM_SO_HCI=lib/libbt-hci.so
ORIG_SO_HCI=lib/libbt-hcio.so

NORM_SO_VEN=vendor/lib/libbt-vendor.so
ORIG_SO_VEN=vendor/lib/libbt-vendoro.so

NORM_API_XML=etc/audio_platform_info.xml
ORIG_API_XML=etc/audio_platform_info.xml.orig

case "$1" in
  backup)
    backup_file $S/"$NORM_SO_HCI"       # Backup what is presumed to be our modified libbt-hci.so (If not, restore does nothing)
    backup_file $S/"$NORM_SO_VEN"       # Backup libbt-vendor.so
    backup_file $S/"$NORM_API_XML"      # Backup audio_platform_info.xml
  ;;
  restore)
    [ -f "$C/$S/$NORM_SO_HCI" ]  && mv $S/"$NORM_SO_HCI" $S/"$ORIG_SO_HCI"      # If libbt-hci.so exists, move the new one (from just flashed ROM) to special name for original (append 'o')
    [ -f "$C/$S/$NORM_SO_HCI" ]  && restore_file $S/"$NORM_SO_HCI" ""           # If libbt-hci.so exists, restore Spirit2 variant
    [ -f "$C/$S/$NORM_SO_VEN" ]  && mv $S/"$NORM_SO_VEN" $S/"$ORIG_SO_VEN"      # Same for libbt-vendor.so
    [ -f "$C/$S/$NORM_SO_VEN" ]  && restore_file $S/"$NORM_SO_VEN" ""
    [ -f "$C/$S/$NORM_API_XML" ] && mv $S/"$NORM_API_XML" $S/"$ORIG_API_XML"    # Same for audio_platform_info.xml
    [ -f "$C/$S/$NORM_API_XML" ] && restore_file $S/"$NORM_API_XML" ""
    ls -l /fff
    #[ -f "$S1_SO_HCI" ] || [ -f "$S2_SO_HCI" ] && [ -f "$C/$S/$NORM_SO_HCI" ] && mv $S/"$NORM_SO_HCI" $S/"$ORIG_SO_HCI"
    #[ -f "$S1_SO_HCI" ] || [ -f "$S2_SO_HCI" ] && [ -f "$C/$S/$NORM_SO_HCI" ] && restore_file $S/"$NORM_SO_HCI" ""
    #[ -f "$S1_SO_HCI" ]                    && [ -f "$C/$S/$NORM_SO_HCI" ] && cp "$S1_SO_HCI" $S/"$NORM_SO_HCI"
    #[ -f "$S2_SO_HCI" ]                    && [ -f "$C/$S/$NORM_SO_HCI" ] && cp "$S2_SO_HCI" $S/"$NORM_SO_HCI"
  ;;
  pre-backup)
    # Stub
  ;;
  post-backup)
    # Stub
  ;;
  pre-restore)
    # Stub
  ;;
  post-restore)
    # Stub
  ;;
esac
