#!/sbin/sh
#
# /system/addon.d/99-spirit.sh (root:root 755)
# During an upgrade, this script backs up Spirit-related files,
# /system is formatted and reinstalled, then the files are restored.
#

. /tmp/backuptool.functions

FILE=lib/hw/audio.primary.smdk4x12.so
#S1_SO_HCI=/data/data/com.mikersmicros.fm_unlock/lib/libbt-hci.so
#S2_SO_HCI=/data/data/fm.a2d.s2/lib/libbt-hci.so

NORM_SO_HCI=lib/libbt-hci.so
ORIG_SO_HCI=lib/libbt-hcio.so

NORM_SO_VEN=vendor/lib/libbt-vendor.so
ORIG_SO_VEN=vendor/lib/libbt-vendoro.so


case "$1" in
  backup)
    backup_file $S/"$NORM_SO_HCI"
  ;;
  restore)
    [ -f "$C/$S/$NORM_SO_HCI" ] && mv $S/"$NORM_SO_HCI" $S/"$ORIG_SO_HCI"
    [ -f "$C/$S/$NORM_SO_HCI" ] && restore_file $S/"$NORM_SO_HCI" ""
    #[ -f "$S1_SO_HCI" ] || [ -f "$S2_SO_HCI" ] && [ -f "$C/$S/$NORM_SO_HCI" ] && mv $S/"$NORM_SO_HCI" $S/"$ORIG_SO_HCI"
    #[ -f "$S1_SO_HCI" ] || [ -f "$S2_SO_HCI" ] && [ -f "$C/$S/$NORM_SO_HCI" ] && restore_file $S/"$NORM_SO_HCI" ""
    #[ -f "$S1_SO_HCI" ]                    && [ -f "$C/$S/$NORM_SO_HCI" ] && cp "$S1_SO_HCI" $S/"$NORM_SO_HCI"
    #[ -f "$S2_SO_HCI" ]                    && [ -f "$C/$S/$NORM_SO_HCI" ] && cp "$S2_SO_HCI" $S/"$NORM_SO_HCI"
    [ -f "$C/$S/$NORM_SO_VEN" ] && mv $S/"$NORM_SO_VEN" $S/"$ORIG_SO_VEN"
    [ -f "$C/$S/$NORM_SO_VEN" ] && restore_file $S/"$NORM_SO_VEN" ""
  ;;
  pre-backup)
    # Stub
  ;;
  post-backup)
    # Stub
  ;;
  pre-restore)
    # Stub
  ;;
  post-restore)
    # Stub
  ;;
esac
